baseURL = "https://imroots.vercel.app/"
languageCode = "en-us"
title = "上下左右"
theme = "ivy"
disqusShortname = "上下左右"
hasCJKLanguage = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
  posts = "/posts/:year/:month/:slug/"
  newsletter = "/newsletter/:year/:month/:slug/"

#[menu]
#  [[menu.main]]
#  name="写作"
#  url="/categories/"
#  weight="1"

  

[params]
  # description abou this website
  description = "醉后不知天在水 满船清梦压星河"
  footer = "&copy; [王上下](https://imroots.vercel.app) | @2018 - 2022"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
  highlightjsVersion = "9.12.0"
[params.waline]
	enable = true

[blackfriday]
extensionsmask = [ "noIntraEmphasis" ]
fractions = false

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
autoHeadingIDType = "blackfriday"

[markup.tableOfContents]
startLevel = 1